// UI text lives here, keyed, so localisation is a matter of adding tables — not editing UI code.

const en = {
  perSec: '/sec',
  upgrade: 'Upgrade',
  hatch: 'Hatch egg',
  unlock: 'Unlock',
  maxed: 'MAX',
  level: 'Lv {n}',
  ticket: 'Ticket',
  dinos: 'Dinos',
  visitors: 'Visitors',
  entryFee: 'Entry fee',
  entrance: 'Entrance',
  entranceSub: 'More visitors, higher entry fee',
  nextMilestone: 'Next milestone: Lv {n}',
  milestoneReward: 'x{m} income',
  unlockFirst: 'Unlock {name} first',
  notEnough: 'Not enough coins',
  newDino: 'New dinosaur!',
  hatched: 'A new {name} hatched!',
  milestone: 'Milestone!',
  boost: '2x Income',
  boostWatch: 'Watch ad',
  boostActive: 'Boost active',
  welcomeBack: 'Welcome back!',
  offlineEarned: 'Your park earned this while you were away ({t})',
  collect: 'Collect',
  collectDouble: 'Collect x2',
  settings: 'Settings',
  sound: 'Sound effects',
  music: 'Music',
  haptics: 'Vibration',
  resetProgress: 'Reset progress',
  resetConfirm: 'Reset all progress? This cannot be undone.',
  tutorialUpgrade: 'Tap to upgrade!',
  close: 'Close',
  boostStarted: 'Income doubled for {t}!',
  adFailed: 'Ad not available right now — try again soon',
  saveRecovered: 'Your save was repaired',
  feed: 'Feed',
  dirty: 'Needs cleaning',
  catch: 'Catch!',
  claim: 'Claim',
  questLevel: 'Upgrade {name} to Lv {n}',
  questDinos: 'Have {n} {name} dinos',
  questUnlock: 'Unlock {name}',
  questEntrance: 'Upgrade the Entrance to Lv {n}',
  questFeed: 'Feed hungry dinos {n}x',
  questClean: 'Clean up {n} dino droppings',
  questTip: 'Collect {n} visitor tips',
  questGift: 'Catch {n} pterodactyl gift',
  questGifts: 'Catch {n} pterodactyl gifts',
  questRoar: 'Tap dinos to make them roar {n}x',
  questDone: 'Quest complete!',
  hintFeed: 'Wait for the meat bubble over an enclosure',
  hintClean: 'Tap droppings inside an enclosure',
  hintTip: 'Tap a bubble above a visitor',
  hintGift: 'Watch the sky for a pterodactyl',
  hintRoar: 'Tap any dinosaur',
};

export type StringKey = keyof typeof en;

export function t(key: StringKey, params: Record<string, string | number> = {}): string {
  return en[key].replace(/\{(\w+)\}/g, (_, k: string) => String(params[k] ?? ''));
}
