using System.Globalization;
using System.Text;
using DinoRush.Core;

namespace DinoRush.AssetForge;

// Writes a MeshBuffer as Wavefront OBJ. OBJ carries no skinning and no animation, which is
// exactly right for what this is for: looking at a shape. Anything that needs the rig goes
// through Unity, not through here.
public static class ObjWriter
{
    public static void Write(string path, MeshBuffer mesh, string name)
    {
        var text = new StringBuilder();
        var culture = CultureInfo.InvariantCulture;

        text.AppendLine($"# {name} — generated by DinoRush AssetForge");
        text.AppendLine($"# {mesh.VertexCount} vertices, {mesh.TriangleCount} triangles");
        text.AppendLine($"o {name}");

        foreach (var p in mesh.Positions)
            text.AppendLine($"v {p.X.ToString("F5", culture)} {p.Y.ToString("F5", culture)} {p.Z.ToString("F5", culture)}");

        foreach (var uv in mesh.Uvs)
            text.AppendLine($"vt {uv.X.ToString("F5", culture)} {uv.Y.ToString("F5", culture)}");

        foreach (var n in mesh.Normals)
            text.AppendLine($"vn {n.X.ToString("F5", culture)} {n.Y.ToString("F5", culture)} {n.Z.ToString("F5", culture)}");

        for (int t = 0; t < mesh.Triangles.Count; t += 3)
        {
            // OBJ indices are 1-based.
            int a = mesh.Triangles[t] + 1;
            int b = mesh.Triangles[t + 1] + 1;
            int c = mesh.Triangles[t + 2] + 1;
            text.AppendLine($"f {a}/{a}/{a} {b}/{b}/{b} {c}/{c}/{c}");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, text.ToString());
    }
}
